import { Montserrat, Great_Vibes } from "next/font/google"
import "./globals.css"
import Header from "./_components/Header"
import Footer from "./_components/Footer"
import { Toaster } from "@/components/ui/sonner"

const monst = Montserrat({
  subsets: ["latin"],
})

const great = Great_Vibes({
  subsets: ["latin"],
  weight: "400",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={` ${monst.className} ${monst.className} `}>
      <body>
        <div>
          <Header />
          {children}
          <Toaster />
        </div>
        <Footer />
      </body>
    </html>
  )
}
